name: virtual_isl_dictionary
description: An application that uses a virtual hand model and a series of pre-programmed movements to display ISL signs on request.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_statusbarcolor: ^0.2.3
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_unity_widget: ^0.1.6+8
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
